In [1]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
# =========================
# 1. Load Dataset
# =========================

df = pd.read_csv("german_credit_data.csv")

print("Shape:", df.shape)
print(df.head())

Shape: (1000, 11)
   Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little
1           1   22  female    2     own          little         moderate
2           2   49    male    1     own          little              NaN
3           3   45    male    2    free          little           little
4           4   53    male    2    free          little           little

   Credit amount  Duration              Purpose  Risk
0           1169         6             radio/TV  good
1           5951        48             radio/TV   bad
2           2096        12            education  good
3           7882        42  furniture/equipment  good
4           4870        24                  car   bad

In [3]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [4]:
# =========================
# 2. Basic Cleaning
# =========================

# Drop unnecessary column
if "Unnamed: 0" in df.columns:
    df.drop(columns=["Unnamed: 0"], inplace=True)

# Handle missing values
# Fill categorical with mode
for col in df.select_dtypes(include="object").columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Fill numerical with median
for col in df.select_dtypes(include=np.number).columns:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\Aditya_Bansal\AppData\Local\Temp\ipykernel_9608\2519388474.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\Aditya_Bansal\AppData\Local\Temp\ipykernel_9608\2519388474.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Aditya_Bansal\AppData\Local\Temp\ipykernel_9608\2519388474.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Aditya_Bansal\AppData\Local\Temp\ipykernel_9608\2519388474.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Aditya_Bansal\AppData\Local\Temp\ipykernel_9608\2519388474.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
df.head()

In [14]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk,AgeGroup
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,1,Senior
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,0,Young
2,2,49,male,1,own,little,NaN,2096,12,education,1,Adult
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1,Adult
4,4,53,male,2,free,little,little,4870,24,car,0,Adult

In [15]:
# =========================
# 3. Identify Target
# =========================

# Kaggle dataset uses 'Risk' as target
# good -> 1, bad -> 0
df["Risk"] = df["Risk"].map({"good": 1, "bad": 0})

In [16]:
# =========================
# 4. Sensitive Attributes (IMPORTANT)
# =========================

# Gender is directly available
sensitive_features = ["Sex", "Age"]

# Create age groups for fairness
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 25, 60, 100],
    labels=["Young", "Adult", "Senior"]
)

In [17]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk,AgeGroup
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,NaN,Senior
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,NaN,Young
2,2,49,male,1,own,little,NaN,2096,12,education,NaN,Adult
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,NaN,Adult
4,4,53,male,2,free,little,little,4870,24,car,NaN,Adult

In [ ]:
# =========================
# 5. Encode Categorical Features
# =========================

categorical_cols = df.select_dtypes(include="object").columns.tolist()
categorical_cols.remove("Risk")

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

ValueError: list.remove(x): x not in list

In [ ]:
# =========================
# 6. Feature / Target Split
# =========================

X = df_encoded.drop(columns=["Risk"])
y = df_encoded["Risk"]

In [7]:
# =========================
# 7. Train-Test Split
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

NameError: name 'X' is not defined

In [8]:
# =========================
# 8. Feature Scaling
# =========================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

NameError: name 'X_train' is not defined

In [ ]:
# =========================
# 9. Output Summary
# =========================

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

print("Sensitive Features:", sensitive_features)